version: '3'

tasks:
  # Django API tasks
  api:migrate:
    dir: api
    cmds:
      - python manage.py migrate

  api:makemigrations:
    dir: api
    cmds:
      - python manage.py makemigrations

  api:shell:
    dir: api
    cmds:
      - python manage.py shell

  api:runserver:
    dir: api
    cmds:
      - python manage.py runserver --port 12319

  # Electron app tasks
  app:start:
    dir: client/
    cmds:
      - npm start

  app:build:
    dir: client/
    cmds:
      - npm run make

  app:package:
    dir: client/
    cmds:
      - npm run package

  # Combined tasks
  dev:
    deps: [ api:runserver, app:start ]
    cmds:
      - echo "Started development environment..."

  install:
    cmds:
      - uv install
      - npm install

  test:
    env:
      DJANGO_SETTINGS_MODULE: agentx_api.settings
    cmds:
      - python api/manage.py test
