version: '3'

tasks:
  api:migrate:
    dir: api
    cmds:
      - uv run python manage.py migrate

  api:makemigrations:
    dir: api/
    cmds:
      - uv run python manage.py makemigrations

  api:shell:
    dir: api/
    cmds:
      - uv run python manage.py shell

  api:runserver:
    dir: api/
    cmds:
      - uv run python manage.py runserver 127.0.0.1:12319

  client:start:
    deps: [ client:build]
    dir: client/
    cmds:
      - bunx next start

  client:build:
    dir: client/
    cmds:
      - bunx next build

  client:dev:
    dir: client/
    cmds:
      - bun run dev

  dev:
    deps: [api:runserver, client:dev]
    cmd: echo SERVER FAILOVER; Check logs for errors

  install:api:
    cmds:
      - uv sync

  install:client:
    dir: client/
    cmds:
      - bun install

  install:
    cmds:
      - task: install:api
      - task: install:client

  test:
    env:
      DJANGO_SETTINGS_MODULE: agentx_api.settings
    cmds:
      - uv run python api/manage.py test
