-- Migration 0001: Initial schema
-- Already applied via queries/postgres_builder.sql on fresh installs.
-- This file exists as a marker so the migration runner knows version 1 is accounted for.
-- DO NOT add statements here — the baseline schema lives in postgres_builder.sql.
