#!/usr/bin/env python3
"""
Generate the Settings Reference docs page from the settings registry.

The page and the settings UI read the same source: `settings_help.yaml` for the
prose, `settings_registry.py` for constraints and tiers, and DEFAULT_CONFIG /
the memory kit's pydantic Settings for types and defaults. Neither surface
authors anything of its own, so the documentation cannot drift from what the app
actually does — which is the whole point of the exercise.

Deliberately **pure**: this imports declarations only and never calls
`get_config_manager()` or `get_settings()`. Reading live config here would bake
one machine's values into a committed page and make the output depend on whose
laptop ran it.

    python3 scripts/gen_settings_reference.py            # write the page
    python3 scripts/gen_settings_reference.py --check    # verify it's current

`--check` warns on drift (regenerate and commit) and errors when the page is
missing entirely — matching the severity convention the other docs checks use:
a stale generated artifact should degrade, never lie.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PAGE = REPO / "docs-site/src/content/docs/getting-started/settings-reference.md"

# Import the API package without booting Django (no settings, no DB).
sys.path.insert(0, str(REPO / "api"))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "agentx_api.settings")

BANNER = (
    "<!-- GENERATED by scripts/gen_settings_reference.py — do not edit by hand.\n"
    "     Prose lives in api/agentx_ai/settings_help.yaml; bounds and tiers in\n"
    "     api/agentx_ai/settings_registry.py. Run `task docs:gen:settings`. -->"
)

FRONTMATTER = (
    "---\n"
    "title: Settings Reference\n"
    "description: Every user-tunable setting in AgentX — what it does, where it "
    "lives, its default, and how to change it.\n"
    "---"
)

INTRO = """\
# Settings Reference

Every setting the app exposes, generated from the same declarations the settings
screen reads. If a setting is described here, that description is the one you'll
see beside the control; if it isn't listed here, the app doesn't offer it.

**How this page is laid out.** One heading per settings screen, in nav order, so
this reads the way the app does. Settings written up in full appear under their
screen; the rest are tabulated beneath them and are being written up screen by
screen.

**Where things are stored.** `config` settings live in `data/config.json` and are
written through `POST /api/config/update`. `memory` settings live in
`data/memory_settings.json` and are written through the two `/api/memory/*`
settings endpoints. A setting with no write route is read-only over the API —
set it in `.env` or the settings file directly, and restart.

**Defaults.** Every value below ships with the default shown. Changing nothing
leaves you on a working configuration; the settings screen marks anything you've
moved and offers to put it back.
"""

# Prose fields, in reading order, with the heading each gets on the page.
HELP_SECTIONS = [
    ("what", "What it is"),
    ("how", "How it works"),
    ("why", "When to change it"),
    ("manage", "Managing it"),
]

TIER_NOTE = {
    # Deliberately not "behind the disclosure in Settings" — that was true of
    # the one section this started with and is not a promise every screen keeps.
    "advanced": "Advanced — most installs never need to change this.",
    "experimental": "Experimental — unproven; may change or be withdrawn.",
}


def _fmt(value: object) -> str:
    """Render a default for a table cell."""
    if value is None:
        return "—"
    if isinstance(value, bool):
        return "`true`" if value else "`false`"
    if value == "":
        return "*(empty)*"
    if isinstance(value, (list, dict)):
        return "*(structured)*" if value else "*(empty)*"
    text = str(value)
    if len(text) > 48:
        text = text[:45] + "…"
    return f"`{text}`"


def _constraint_text(entry: dict) -> str:
    c = entry.get("constraints") or {}
    bits = []
    if c.get("min") is not None or c.get("max") is not None:
        bits.append(f"{c.get('min', '−∞')} to {c.get('max', '∞')}")
    if c.get("enum"):
        bits.append(" / ".join(f"`{v}`" for v in c["enum"]))
    if c.get("unit"):
        bits.append(c["unit"])
    return ", ".join(bits)


#: The bucket for settings no screen renders — read-only plumbing, and keys set
#: elsewhere in the app. Sorts last; a slug no reader would recognise otherwise.
OTHER = "_other"


def build_entries() -> list[dict]:
    """Every setting, with its declared metadata and authored help."""
    from agentx_ai.settings_manifest import build_reference_entries

    return build_reference_entries()


def _render_setting(entry: dict, parts: list[str]) -> None:
    """The long form: one fully-authored setting."""
    help_text = entry["help"]
    parts.append(f"### `{entry['key']}`\n")
    if help_text.get("summary"):
        parts.append(f"*{help_text['summary']}*\n")

    meta = [f"**Default:** {_fmt(entry['default'])}"]
    if rng := _constraint_text(entry):
        meta.append(f"**Range:** {rng}")
    if entry.get("writable_via"):
        meta.append(f"**Set via:** `{entry['writable_via']}`")
    else:
        meta.append("**Read-only** over the API")
    if note := TIER_NOTE.get(entry.get("tier") or ""):
        meta.append(note)
    parts.append(" · ".join(meta) + "\n")

    for field, heading in HELP_SECTIONS:
        body = (help_text.get(field) or "").strip()
        if body:
            parts.append(f"**{heading}.** {body}\n")


def _render_table(rows: list[dict], parts: list[str]) -> None:
    """The whole table as ONE part.

    Blocks are joined with a blank line between them, and a Markdown table needs
    its rows contiguous — appending row-by-row rendered every row as a paragraph
    of literal pipes. (It did, on the page this replaces.)
    """
    lines = ["| Setting | Type | Default | Store | Set via |",
             "| --- | --- | --- | --- | --- |"]
    for entry in sorted(rows, key=lambda e: e["key"]):
        route = f"`{entry['writable_via']}`" if entry.get("writable_via") else "read-only"
        default = "*(secret)*" if entry["secret"] else _fmt(entry["default"])
        lines.append(
            f"| `{entry['key']}` | {entry['type']} | {default} "
            f"| {entry['store']} | {route} |"
        )
    parts.append("\n".join(lines))


def render(entries: list[dict]) -> str:
    from agentx_ai.settings_manifest import build_sections

    by_section: dict[str, list[dict]] = {}
    for entry in entries:
        by_section.setdefault(entry.get("ui_section") or OTHER, []).append(entry)

    parts = [FRONTMATTER, BANNER, INTRO]

    # Screen order comes from the registry, so this page and the nav agree on
    # both what the screens are and what they're called.
    sections = build_sections(entries)
    order = [s["id"] for s in sections if s["id"] in by_section] + [OTHER]
    blurbs = {s["id"]: s for s in sections}

    for section_id in order:
        rows = by_section.get(section_id)
        if not rows:
            continue
        meta = blurbs.get(section_id)
        if section_id == OTHER:
            parts.append("## Not shown in Settings\n")
            parts.append(
                "Read-only plumbing, plus a few values set elsewhere in the app "
                "rather than on a settings screen."
            )
        else:
            parts.append(f"## {meta['label'] if meta else section_id}\n")
            blurb = (meta or {}).get("help") or {}
            if blurb.get("summary"):
                parts.append(f"*{blurb['summary']}*\n")
            for field in ("what", "why"):
                if body := (blurb.get(field) or "").strip():
                    parts.append(body + "\n")

        documented = [e for e in rows if e.get("help")]
        rest = [e for e in rows if not e.get("help")]

        for entry in sorted(documented, key=lambda e: e["key"]):
            _render_setting(entry, parts)

        if rest:
            if documented:
                # Not always literally "on the screen": a section's config roots
                # can hold read-only keys no control renders. Say what the row
                # means rather than implying every one has a knob.
                parts.append(
                    "**Also in this area**, not yet written up. A `read-only` "
                    "route means the value is set in `.env` or the settings file "
                    "rather than through the API:\n"
                )
            _render_table(rest, parts)

    parts.append(
        "## Related\n\n"
        "- [Configuration](./configuration.md) — environment variables, "
        "connector files, and the layout of the config files themselves."
    )
    # Parts are written with or without trailing newlines depending on what
    # reads best in source; normalise so the page has exactly one blank line
    # between blocks.
    return "\n\n".join(p.strip("\n") for p in parts if p.strip()).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify the committed page matches the declarations")
    parser.add_argument("--strict", action="store_true",
                        help="treat drift as an error (used by the docs gate in CI)")
    args = parser.parse_args()

    rendered = render(build_entries())

    if not args.check:
        PAGE.parent.mkdir(parents=True, exist_ok=True)
        PAGE.write_text(rendered, encoding="utf-8")
        print(f"✅ wrote {PAGE.relative_to(REPO)}")
        return 0

    if not PAGE.exists():
        print(f"❌ {PAGE.relative_to(REPO)} is missing — run `task docs:gen:settings`")
        return 1

    if PAGE.read_text(encoding="utf-8") != rendered:
        print(f"⚠️  {PAGE.relative_to(REPO)} is out of date — "
              f"run `task docs:gen:settings` and commit the result")
        return 1 if args.strict else 0

    print("✅ settings reference is current.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
