#!/usr/bin/env python3
"""
Generate the Settings Reference docs page from the settings registry.

The page and the settings UI read the same source: `settings_help.yaml` for the
prose, `settings_registry.py` for constraints and tiers, and DEFAULT_CONFIG /
the memory kit's pydantic Settings for types and defaults. Neither surface
authors anything of its own, so the documentation cannot drift from what the app
actually does — which is the whole point of the exercise.

Deliberately **pure**: this imports declarations only and never calls
`get_config_manager()` or `get_settings()`. Reading live config here would bake
one machine's values into a committed page and make the output depend on whose
laptop ran it.

    python3 scripts/gen_settings_reference.py            # write the page
    python3 scripts/gen_settings_reference.py --check    # verify it's current

`--check` warns on drift (regenerate and commit) and errors when the page is
missing entirely — matching the severity convention the other docs checks use:
a stale generated artifact should degrade, never lie.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PAGE = REPO / "docs-site/src/content/docs/getting-started/settings-reference.md"

# Import the API package without booting Django (no settings, no DB).
sys.path.insert(0, str(REPO / "api"))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "agentx_api.settings")

BANNER = (
    "<!-- GENERATED by scripts/gen_settings_reference.py — do not edit by hand.\n"
    "     Prose lives in api/agentx_ai/settings_help.yaml; bounds and tiers in\n"
    "     api/agentx_ai/settings_registry.py. Run `task docs:gen:settings`. -->"
)

FRONTMATTER = (
    "---\n"
    "title: Settings Reference\n"
    "description: Every user-tunable setting in AgentX — what it does, where it "
    "lives, its default, and how to change it.\n"
    "---"
)

INTRO = """\
# Settings Reference

Every setting the app exposes, generated from the same declarations the settings
screen reads. If a setting is described here, that description is the one you'll
see beside the control; if it isn't listed here, the app doesn't offer it.

**Where things are stored.** `config` settings live in `data/config.json` and are
written through `POST /api/config/update`. `memory` settings live in
`data/memory_settings.json` and are written through the two `/api/memory/*`
settings endpoints. A setting with no write route is read-only over the API —
set it in `.env` or the settings file directly, and restart.

**Defaults.** Every value below ships with the default shown. Changing nothing
leaves you on a working configuration; the settings screen marks anything you've
moved and offers to put it back.
"""

# Prose fields, in reading order, with the heading each gets on the page.
HELP_SECTIONS = [
    ("what", "What it is"),
    ("how", "How it works"),
    ("why", "When to change it"),
    ("manage", "Managing it"),
]

TIER_NOTE = {
    "advanced": "Advanced — behind the disclosure in Settings.",
    "experimental": "Experimental — unproven; may change or be withdrawn.",
}


def _fmt(value: object) -> str:
    """Render a default for a table cell."""
    if value is None:
        return "—"
    if isinstance(value, bool):
        return "`true`" if value else "`false`"
    if value == "":
        return "*(empty)*"
    if isinstance(value, (list, dict)):
        return "*(structured)*" if value else "*(empty)*"
    text = str(value)
    if len(text) > 48:
        text = text[:45] + "…"
    return f"`{text}`"


def _constraint_text(entry: dict) -> str:
    c = entry.get("constraints") or {}
    bits = []
    if c.get("min") is not None or c.get("max") is not None:
        bits.append(f"{c.get('min', '−∞')} to {c.get('max', '∞')}")
    if c.get("enum"):
        bits.append(" / ".join(f"`{v}`" for v in c["enum"]))
    if c.get("unit"):
        bits.append(c["unit"])
    return ", ".join(bits)


def build_entries() -> list[dict]:
    """Every setting, with its declared metadata and authored help."""
    from agentx_ai.settings_manifest import build_reference_entries

    return build_reference_entries()


def render(entries: list[dict]) -> str:
    from agentx_ai.settings_registry import ui_section_label

    by_section: dict[str, list[dict]] = {}
    for entry in entries:
        by_section.setdefault(entry.get("ui_section") or "_other", []).append(entry)

    documented = [e for e in entries if e.get("help")]
    parts = [FRONTMATTER, BANNER, INTRO]

    # Fully-documented settings get the long form; everything else is tabulated.
    if documented:
        parts.append(
            "## Documented settings\n\n"
            "These carry the full write-up. The rest of the catalogue is "
            "tabulated below, and is being written up section by section."
        )
        for entry in sorted(documented, key=lambda e: (e.get("ui_section") or "", e["key"])):
            help_text = entry["help"]
            parts.append(f"### `{entry['key']}`\n")
            if help_text.get("summary"):
                parts.append(f"*{help_text['summary']}*\n")

            meta = [f"**Default:** {_fmt(entry['default'])}"]
            if rng := _constraint_text(entry):
                meta.append(f"**Range:** {rng}")
            if entry.get("ui_section"):
                meta.append(f"**Found in:** {ui_section_label(entry['ui_section'])}")
            if entry.get("writable_via"):
                meta.append(f"**Set via:** `{entry['writable_via']}`")
            if note := TIER_NOTE.get(entry.get("tier") or ""):
                meta.append(note)
            parts.append(" · ".join(meta) + "\n")

            for field, heading in HELP_SECTIONS:
                body = (help_text.get(field) or "").strip()
                if body:
                    parts.append(f"**{heading}.** {body}\n")

    parts.append("## Full catalogue\n")
    parts.append(
        "Every remaining setting, by the screen it appears on. A blank write "
        "route means the value is read-only over the API."
    )

    # "_other" sorts first, which is wrong — the settings you can actually reach
    # should lead, with the read-only plumbing last.
    for section in sorted(by_section, key=lambda s: (s == "_other", s)):
        rows = sorted(by_section[section], key=lambda e: e["key"])
        title = ui_section_label(None if section == "_other" else section)
        parts.append(f"### {title}\n")
        parts.append("| Setting | Type | Default | Store | Set via |")
        parts.append("| --- | --- | --- | --- | --- |")
        for entry in rows:
            route = f"`{entry['writable_via']}`" if entry.get("writable_via") else "read-only"
            default = "*(secret)*" if entry["secret"] else _fmt(entry["default"])
            parts.append(
                f"| `{entry['key']}` | {entry['type']} | {default} "
                f"| {entry['store']} | {route} |"
            )
        parts.append("")

    parts.append(
        "## Related\n\n"
        "- [Configuration](./configuration.md) — environment variables, "
        "connector files, and the layout of the config files themselves."
    )
    # Parts are written with or without trailing newlines depending on what
    # reads best in source; normalise so the page has exactly one blank line
    # between blocks.
    return "\n\n".join(p.strip("\n") for p in parts if p.strip()).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify the committed page matches the declarations")
    parser.add_argument("--strict", action="store_true",
                        help="treat drift as an error (used by the docs gate in CI)")
    args = parser.parse_args()

    rendered = render(build_entries())

    if not args.check:
        PAGE.parent.mkdir(parents=True, exist_ok=True)
        PAGE.write_text(rendered, encoding="utf-8")
        print(f"✅ wrote {PAGE.relative_to(REPO)}")
        return 0

    if not PAGE.exists():
        print(f"❌ {PAGE.relative_to(REPO)} is missing — run `task docs:gen:settings`")
        return 1

    if PAGE.read_text(encoding="utf-8") != rendered:
        print(f"⚠️  {PAGE.relative_to(REPO)} is out of date — "
              f"run `task docs:gen:settings` and commit the result")
        return 1 if args.strict else 0

    print("✅ settings reference is current.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
