// Landing-page copy + data. Single source for the marketing surface; kept separate
// from nav.ts (navigation structure) but reusing the same --c-* accent tokens.
// Ported from the design handoff (landing.jsx / common.jsx / system-map.jsx).

/** Product version — keep in sync with ../../../versions.yaml (api.version). */
export const version = '0.21.245';

export type Feature = {
  key: string;
  label: string;
  desc: string;
  color: string; // a --c-* token, referenced via var()
  tag: string;
  href: string; // where the rail card / chip links in the docs
};

// The eight runtime subsystems. Used by the subsystems rail, the system-map copy
// chips, and the constellation. `key` drives the constellation node order.
export const FEATURES: Feature[] = [
  {
    key: 'agent',
    label: 'Agent',
    desc: 'Per-request orchestrator. Sessions, context budgeting, tool loop, output parsing.',
    color: 'var(--c-agent)',
    tag: 'agent/core.py',
    href: '/docs/architecture/overview',
  },
  {
    key: 'reasoning',
    label: 'Reasoning',
    desc: 'Six thinking patterns — native, step-by-step, step-back, reflection, deep reflection, and consensus — auto-selected per task, with a Tree-of-Thought / ReAct kit for offline runs.',
    color: 'var(--c-reasoning)',
    tag: '6 patterns',
    href: '/docs/features/reasoning',
  },
  {
    key: 'drafting',
    label: 'Drafting',
    desc: 'Speculative decoding, multi-stage pipelines, N-best candidates.',
    color: 'var(--c-drafting)',
    tag: 'spec · pipe · cand',
    href: '/docs/features/reasoning#advanced-multi-model-drafting',
  },
  {
    key: 'mcp',
    label: 'MCP Client',
    desc: 'Connect to external tool servers over stdio, SSE, or streamable HTTP.',
    color: 'var(--c-mcp)',
    tag: 'stdio · sse · http',
    href: '/docs/features/mcp',
  },
  {
    key: 'providers',
    label: 'Providers',
    desc: 'One interface across LM Studio, Anthropic, OpenAI, OpenRouter, and Vercel AI Gateway — swap models per request.',
    color: 'var(--c-providers)',
    tag: '5 providers · byo models',
    href: '/docs/features/providers',
  },
  {
    key: 'prompts',
    label: 'Prompts',
    desc: 'Profile-based composition with a global prompt layer. Sections compose at runtime.',
    color: 'var(--c-prompts)',
    tag: 'profiles · sections',
    href: '/docs/features/prompts',
  },
  {
    key: 'memory',
    label: 'Memory',
    desc: 'Four memory types with five recall techniques, per-agent self-knowledge, and background consolidation.',
    color: 'var(--c-memory)',
    tag: '4-type · 5 recall',
    href: '/docs/features/memory',
  },
  {
    key: 'orchestration',
    label: 'Orchestration',
    desc: 'Agent Teams — a lead hands subtasks to specialist teammates over a shared channel, with @-mention routing and ad-hoc agent-to-agent delegation.',
    color: 'var(--c-translation)',
    tag: 'teams · delegate',
    href: '/docs/features/multi-agent',
  },
];

// The hero's multi-agent trace now replays a REAL recorded run — see
// config/hero-run.json (generated by scripts/distill-hero-run.mjs) and TraceConsole.astro.

// ── Hero stat row ───────────────────────────────────────────────────────────
export const HERO_STATS: { l: string; v: string }[] = [
  { l: 'deploy', v: 'Self-hosted · your infra' },
  { l: 'backend', v: 'Django 5.2' },
  { l: 'client', v: 'Tauri v2 · React 19' },
  { l: 'memory', v: 'Neo4j · pgvector · Redis' },
  { l: 'license', v: 'MIT' },
];

// ── Lifecycle band ────────────────────────────────────────────────────────
export type LifecycleStep = { c: string; k: string; l: string; t: string };

export const LIFECYCLE: LifecycleStep[] = [
  { c: 'var(--c-agent)', k: '01', l: 'views.py', t: 'dispatch · session bind' },
  { c: 'var(--c-prompts)', k: '02', l: 'PromptManager', t: 'compose profile + sections (extends)' },
  { c: 'var(--c-memory)', k: '03', l: 'MemoryBundle', t: 'recall · _self_{agent} + _global · hybrid + HyDE' },
  { c: 'var(--c-reasoning)', k: '04', l: 'Reasoning', t: 'select strategy (CoT/ToT/ReAct/Reflection)' },
  { c: 'var(--c-agent)', k: '05', l: 'Team.delegate', t: 'the lead hands subtasks to specialist teammates' },
  { c: 'var(--c-mcp)', k: '06', l: 'ToolExecutor', t: 'stdio · sse · http  →  external MCP' },
  { c: 'var(--c-drafting)', k: '07', l: 'Drafting', t: 'candidate / pipeline / speculative' },
  { c: 'var(--color-ok)', k: '08', l: 'AgentResult', t: 'merge sub-results · parse · persist · respond' },
];

// ── Data layer ────────────────────────────────────────────────────────────
export type Store = { c: string; n: string; d: string };

export const STORES: Store[] = [
  { c: 'var(--c-memory)', n: 'Neo4j 5.15', d: 'entity graphs · semantic + procedural' },
  { c: 'var(--c-agent)', n: 'PostgreSQL + pgvector', d: 'vectors · episodic · audit log' },
  { c: 'var(--c-drafting)', n: 'Redis 7', d: 'working memory cache · session state' },
];

// ── "Why AgentX" — the differentiators band ─────────────────────────────────
export type PillarCard = {
  title: string;
  desc: string;
  color: string; // a --c-* token
  tag: string;
  href: string;
};
export type Pillar = { name: string; lede: string; color: string; cards: PillarCard[] };

export const PILLARS: Pillar[] = [
  {
    name: 'It thinks',
    lede: 'A mind you can watch work — reasoning, memory that learns, and a context window that never overflows.',
    color: 'var(--c-reasoning)',
    cards: [
      {
        title: 'Glassbox, not a black box',
        desc: 'Watch the agent think, call tools, and hand work to teammates — live. The reasoning, every tool call and result, and each delegation stream to screen; nothing happens in the dark.',
        color: 'var(--c-reasoning)',
        tag: 'see everything',
        href: '/docs/architecture/system-design',
      },
      {
        title: 'Memory that actually learns',
        desc: 'Four memory types — episodic, semantic, procedural, and working — with five recall techniques and background consolidation, so agents remember and sharpen across conversations.',
        color: 'var(--c-memory)',
        tag: 'remembers & learns',
        href: '/docs/features/memory',
      },
      {
        title: 'Context that never overflows',
        desc: 'Oversized tool outputs are compressed and stored for retrieval, and Focus-style trajectory compression keeps long tool loops inside the window — so the agent stays coherent on long tasks.',
        color: 'var(--c-drafting)',
        tag: 'stays in the window',
        href: '/docs/features/chat',
      },
      {
        title: 'Prompts you compose',
        desc: "Build an agent's persona from layered, reusable prompt sections over a global base — with an LLM-backed enhancer that sharpens a prompt on demand.",
        color: 'var(--c-prompts)',
        tag: 'shape the persona',
        href: '/docs/features/prompts',
      },
    ],
  },
  {
    name: 'It works as a team',
    lede: 'Not one overloaded assistant — a roster of specialists that delegate, coordinate, and keep you in the loop.',
    color: 'var(--c-agent)',
    cards: [
      {
        title: 'Agent Teams that collaborate',
        desc: 'A lead hands subtasks to specialist teammates over a shared memory channel — with @-mention routing, ad-hoc agent-to-agent delegation, and per-agent tool isolation. Watch them work it out.',
        color: 'var(--c-agent)',
        tag: 'delegate & coordinate',
        href: '/docs/features/multi-agent',
      },
      {
        title: 'Ambassador — a parallel narrator',
        desc: 'A dedicated agent runs alongside your conversation and briefs you on it — by voice or text — without ever entering the transcript. Step away, come back, and ask what your agents have been doing.',
        color: 'var(--c-translation)',
        tag: 'briefs you, live',
        href: '/docs/features/multi-agent',
      },
      {
        title: 'Tools in one line',
        desc: 'Connect external tool servers over MCP, or turn any Python function into an agent tool with a single @register_tool decorator — no separate server for in-process tools.',
        color: 'var(--c-mcp)',
        tag: 'connect & extend',
        href: '/docs/features/mcp',
      },
    ],
  },
  {
    name: "It's yours",
    lede: 'You own the whole stack — the server, the models, and every platform it runs on.',
    color: 'var(--c-providers)',
    cards: [
      {
        title: 'Self-hosted, bring your own models',
        desc: 'Run your own server — no SaaS, no lock-in. One interface across LM Studio, Anthropic, OpenAI, OpenRouter, and Vercel AI Gateway; bring the models you already pay for.',
        color: 'var(--c-providers)',
        tag: 'your server',
        href: '/docs/features/providers',
      },
      {
        title: 'Runs where you do',
        desc: 'One Tauri v2 client across Windows, macOS, and Linux, an Android build (mobile-ready), and a browser / PWA mode. Same app, everywhere you work.',
        color: 'var(--color-accent)',
        tag: 'desktop · mobile · web',
        href: '/docs/getting-started/installation',
      },
      {
        title: 'Open source, yours to keep',
        desc: 'AgentX is MIT-licensed and built in the open — read every line, fork it, and run it as long as you like. No vendor can switch it off.',
        color: 'var(--c-reasoning)',
        tag: 'MIT · open',
        href: 'https://github.com/QR-Madness/agentx',
      },
    ],
  },
];

// ── "Direction" — roadmap teaser ────────────────────────────────────────────
export type DirectionColumn = { k: string; title: string; items: string[] };

export const DIRECTION: DirectionColumn[] = [
  {
    k: 'shipped',
    title: 'Shipped',
    items: [
      'Mobile-Ready Alpha — self-hosted server (auth · prod Docker · clusters) + Tauri v2 desktop/Android',
      'Layered memory — 4 types, 5-technique recall, per-agent self-knowledge, background consolidation',
      'Agent Teams — lead + specialist delegation, @-mention routing, per-agent tool isolation',
      'Ambassador — a parallel briefer with two-way voice (TTS + STT)',
    ],
  },
  {
    k: 'now',
    title: 'Shipping now',
    items: [
      'Ambassador v2 — a conversational, tool-using relay with its own persistent thread',
      'Procedural memory — agents distill and replay "how we work here"',
      'Active recall + memory tuning — closing the query-formulation gap',
    ],
  },
  {
    k: 'next',
    title: 'Next',
    items: [
      'Memory hardening — event-sourced write path, bitemporal facts, a capability registry',
      'File Workspaces & Document RAG — hand agents a corpus, not just memory + web',
      'Settings Advisor + Manifest — a self-tuning control plane',
      'Factory canvas — a visual multi-agent workflow editor',
    ],
  },
];

// ── "Powered by" — open-source shout-out ────────────────────────────────────
export type Dependency = { name: string; href: string };

export const POWERED_BY: Dependency[] = [
  { name: 'Django', href: 'https://www.djangoproject.com/' },
  { name: 'Tauri', href: 'https://tauri.app/' },
  { name: 'React', href: 'https://react.dev/' },
  { name: 'Vite', href: 'https://vite.dev/' },
  { name: 'Tailwind CSS', href: 'https://tailwindcss.com/' },
  { name: 'NLLB-200', href: 'https://huggingface.co/facebook/nllb-200-distilled-600M' },
  { name: 'Hugging Face', href: 'https://huggingface.co/' },
  { name: 'sentence-transformers', href: 'https://www.sbert.net/' },
  { name: 'Neo4j', href: 'https://neo4j.com/' },
  { name: 'PostgreSQL', href: 'https://www.postgresql.org/' },
  { name: 'pgvector', href: 'https://github.com/pgvector/pgvector' },
  { name: 'Redis', href: 'https://redis.io/' },
  { name: 'Model Context Protocol', href: 'https://modelcontextprotocol.io/' },
];
